config/routes.rb
# This file is a part of Redmine CRM (redmine_contacts) plugin,
# customer relationship management plugin for Redmine
#
# Copyright (C) 2010-2017 RedmineUP
# http://www.redmineup.com/
#
# redmine_contacts is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_contacts is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_contacts.  If not, see <http://www.gnu.org/licenses/>.

#custom routes for this plugin
  resources :contacts, :path_names => {:contacts_notes => 'notes'} do
    collection do
      get :bulk_edit, :context_menu, :edit_mails, :contacts_notes
      post :bulk_edit, :bulk_update, :send_mails, :preview_email
      delete :bulk_destroy
    end
    member do
      get 'tabs/:tab' => 'contacts#show', :as => "tabs"
      get 'load_tab' => 'contacts#load_tab', :as => "load_tab"
    end
    resources :contacts_projects, :path => "projects", :only => [:new, :create, :destroy]
  end

  resources :projects do
    resources :contacts, :path_names => {:contacts_notes => 'notes'} do
      collection do
        get :contacts_notes
      end
    end

  end

  resources :projects do
    resources :crm_queries, :only => [:new, :create]
  end

  resources :crm_queries, :except => [:show]

  resources :notes

  match '/contacts_tags', :controller => 'contacts_tags', :action => 'destroy', :via => :delete

  resources :contacts_tags do
    collection do
      post :merge, :context_menucha
      get :context_menu, :merge
    end
  end

  match 'projects/:project_id/contacts/:contact_id/new_task' => 'contacts_issues#new', :via => :post

  match 'contacts/:contact_id/duplicates' => 'contacts_duplicates#index', :via => [:get, :post]

  match 'projects/:project_id/deal_categories/new' => 'deal_categories#new', :via => [:get, :post]


  match 'auto_completes/taggable_tags' => 'auto_completes#taggable_tags', :via => :get, :as => 'auto_complete_taggable_tags'
  match 'auto_completes/contact_tags' => 'auto_completes#contact_tags', :via => :get, :as => 'auto_complete_contact_tags'
  match 'auto_completes/contacts' => 'auto_completes#contacts', :via => :get, :as => 'auto_complete_contacts'
  match 'auto_completes/companies' => 'auto_completes#companies', :via => :get, :as => 'auto_complete_companies'

  match 'users/new_from_contact/:id' => 'users#new_from_contact', :via => :get
  match 'contacts_duplicates/:action' => 'contacts_duplicates', :via => [:get, :post]
  match 'contacts_duplicates/search' => 'contacts_duplicates#search', :via => :get, :as => 'contacts_duplicates_search'
  match 'contacts_issues/:action' => 'contacts_issues', :via => [:get, :post, :delete, :put]
  match 'contacts_vcf/:action' => 'contacts_vcf', :via => [:get, :post]
  match 'deal_contacts/:action' => 'deal_contacts', :via => [:get, :post, :delete]
  match 'deals_tasks/:action' => 'deals_tasks', :via => [:get, :post, :put]
  match 'contacts_settings/:action' => 'contacts_settings', :via => [:get, :post]
  match 'contacts_mailer/:action' => 'contacts_mailer', :via => [:get, :post]
  match 'attachments/contacts_thumbnail/:id(/:size)', :controller => 'attachments', :action => 'contacts_thumbnail', :id => /\d+/, :via => :get

app/controllers/contacts_tags_controller.rb
# This file is a part of Redmine CRM (redmine_contacts) plugin,
# customer relationship management plugin for Redmine
#
# Copyright (C) 2010-2017 RedmineUP
# http://www.redmineup.com/
#
# redmine_contacts is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_contacts is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_contacts.  If not, see <http://www.gnu.org/licenses/>.

class ContactsTagsController < ApplicationController
  unloadable
  before_filter :require_admin, :except => [:index]
  before_filter :find_tag, :only => [:edit, :update]
  before_filter :bulk_find_tags, :only => [:context_menu, :merge, :destroy]

  accept_api_auth :index

  def index
    @tags = Contact.all_tag_counts(:order => :name)
    respond_to do |format|
      format.api
    end
  end

  def edit
  end

  def destroy
    @tags.each do |tag|
      begin
        tag.reload.destroy
        Contact.where("#{Contact.table_name}.cached_tag_list LIKE ?", '%' + tag.name + '%').includes(:tags).each{|c| c.tag_list = c.all_tags_list; c.save}
      rescue ::ActiveRecord::RecordNotFound # raised by #reload if tag no longer exists
        # nothing to do, tag was already deleted (eg. by a parent)
      end
    end
    redirect_back_or_default(:controller => 'settings', :action => 'plugin', :id => 'redmine_contacts', :tab => "tags")
  end

  def update
    old_name = @tag.name
    @tag.name = params[:tag][:name]
    if @tag.save
      Contact.where("#{Contact.table_name}.cached_tag_list LIKE ?", '%' + old_name + '%').includes(:tags).each{|c| c.tag_list = c.all_tags_list; c.save}
      flash[:notice] = l(:notice_successful_update)
      respond_to do |format|
        format.html { redirect_to :controller => 'settings', :action => 'plugin', :id => 'redmine_contacts', :tab => "tags" }
      end
    else
      respond_to do |format|
        format.html { render :action => "edit"}
      end
    end
  end

  def context_menu
    @tag = @tags.first if (@tags.size == 1)
    @back = back_url
    render :layout => false
  end

  def merge
    if request.post? && params[:tag] && params[:tag][:name]
      RedmineCrm::Tagging.transaction do
        tag = RedmineCrm::Tag.where(:name => params[:tag][:name]).first || RedmineCrm::Tag.create(params[:tag])
        RedmineCrm::Tagging.where(:tag_id => @tags.map(&:id)).update_all(:tag_id => tag.id)
        @tags.select{|t| t.id != tag.id}.each do |t|
          t.destroy
          Contact.where("#{Contact.table_name}.cached_tag_list LIKE ?", '%' + t.name + '%').includes(:tags).each{|c| c.tag_list = c.all_tags_list; c.save}
        end
        redirect_to :controller => 'settings', :action => 'plugin', :id => 'redmine_contacts', :tab => "tags"
      end
    end
  end

  private

  def bulk_find_tags
    @tags = RedmineCrm::Tag.where(:id => params[:id] ? [params[:id]] : params[:ids])
    raise ActiveRecord::RecordNotFound if @tags.empty?
  end

  def find_tag
    @tag = RedmineCrm::Tag.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end
end

app/views/contacts_tags/_tags_form.html.erb
<span class="contacts-tags-edit">
   <%= text_field_tag 'contact[tag_list]', "#{@contact.tags.map(&:name).join(',').html_safe}", :size => 10, :class => 'hidden', :id => "allowSpacesTags" %><%= tagsedit_with_source_for('#allowSpacesTags', auto_complete_contact_tags_path(:project_id => @project)) %>
</span>

app/views/contacts_tags/context_menu.html.erb
<ul>
  <% if @tag -%>
    <li><%= link_to l(:button_edit), edit_contacts_tag_path(@tag),
            :class => 'icon-edit' %></li>
  <% else %>
    <li><%= link_to l(:label_crm_megre_tags), merge_contacts_tags_path(:ids => @tags.collect(&:id)),
            :class => 'icon-merge' %></li>
  <% end %>

    <li><%= link_to l(:button_delete), contacts_tags_path(:ids => @tags.collect(&:id), :back_url => @back),
                            :method => :delete, :data => {:confirm => l(:text_are_you_sure)}, :class => 'icon-del' %></li>
</ul>

app/views/contacts_tags/edit.html.erb
<h2><%= link_to l(:contacts_title), {:controller => 'settings', :action => 'plugin', :id => 'redmine_contacts', :tab => "tags"} %> &#187; <%=h (l(:label_tag) + ": " + @tag.name) %></h2>

<%= form_tag(contacts_tag_path(@tag), :class => "tabular", :method => :put) do %>
  <%= error_messages_for 'tag' %>
<div class="box">
  <p>
    <%= label_tag("tag_name", l(:field_name)) %>
    <%= text_field 'tag', 'name'  %>
  </p>
</div>
  <%= submit_tag l(:button_save) %>
<% end %>

app/views/contacts_tags/merge.html.erb
<h2><%= link_to l(:label_crm_tags_plural), {:controller => 'settings', :action => 'plugin', :id => 'redmine_contacts', :tab => "tags"} %> &#187; <%= l(:label_crm_megre_tags) %></h2>
<%= form_tag(merge_contacts_tags_path(:ids => @tags.map(&:id)), :class => "tabular") do %>
  <%= error_messages_for 'tag' %>
  <div class="box">
    <p>
      <label for="tag_name"><%=l(:label_crm_tags_plural)%></label>
      <%= tag_links(@tags.map(&:name)) %>
    </p>
    <p><label for="tag_name"><%=l(:field_name)%></label>
    <%= text_field 'tag', 'name', :value => @tags.first.name  %></p>
  </div>

  <%= submit_tag l(:button_save) %>
<% end %>