config/routes.rb
# This file is a part of Redmine CRM (redmine_contacts) plugin,
# customer relationship management plugin for Redmine
#
# Copyright (C) 2010-2017 RedmineUP
# http://www.redmineup.com/
#
# redmine_contacts is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_contacts is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_contacts.  If not, see <http://www.gnu.org/licenses/>.

#custom routes for this plugin
  resources :contacts, :path_names => {:contacts_notes => 'notes'} do
    collection do
      get :bulk_edit, :context_menu, :edit_mails, :contacts_notes
      post :bulk_edit, :bulk_update, :send_mails, :preview_email
      delete :bulk_destroy
    end
    member do
      get 'tabs/:tab' => 'contacts#show', :as => "tabs"
      get 'load_tab' => 'contacts#load_tab', :as => "load_tab"
    end
    resources :contacts_projects, :path => "projects", :only => [:new, :create, :destroy]
  end

  resources :projects do
    resources :contacts, :path_names => {:contacts_notes => 'notes'} do
      collection do
        get :contacts_notes
      end
    end

  end

  resources :projects do
    resources :crm_queries, :only => [:new, :create]
  end

  resources :crm_queries, :except => [:show]

  resources :notes

  match '/contacts_tags', :controller => 'contacts_tags', :action => 'destroy', :via => :delete

  resources :contacts_tags do
    collection do
      post :merge, :context_menucha
      get :context_menu, :merge
    end
  end

  match 'projects/:project_id/contacts/:contact_id/new_task' => 'contacts_issues#new', :via => :post

  match 'contacts/:contact_id/duplicates' => 'contacts_duplicates#index', :via => [:get, :post]

  match 'projects/:project_id/deal_categories/new' => 'deal_categories#new', :via => [:get, :post]


  match 'auto_completes/taggable_tags' => 'auto_completes#taggable_tags', :via => :get, :as => 'auto_complete_taggable_tags'
  match 'auto_completes/contact_tags' => 'auto_completes#contact_tags', :via => :get, :as => 'auto_complete_contact_tags'
  match 'auto_completes/contacts' => 'auto_completes#contacts', :via => :get, :as => 'auto_complete_contacts'
  match 'auto_completes/companies' => 'auto_completes#companies', :via => :get, :as => 'auto_complete_companies'

  match 'users/new_from_contact/:id' => 'users#new_from_contact', :via => :get
  match 'contacts_duplicates/:action' => 'contacts_duplicates', :via => [:get, :post]
  match 'contacts_duplicates/search' => 'contacts_duplicates#search', :via => :get, :as => 'contacts_duplicates_search'
  match 'contacts_issues/:action' => 'contacts_issues', :via => [:get, :post, :delete, :put]
  match 'contacts_vcf/:action' => 'contacts_vcf', :via => [:get, :post]
  match 'deal_contacts/:action' => 'deal_contacts', :via => [:get, :post, :delete]
  match 'deals_tasks/:action' => 'deals_tasks', :via => [:get, :post, :put]
  match 'contacts_settings/:action' => 'contacts_settings', :via => [:get, :post]
  match 'contacts_mailer/:action' => 'contacts_mailer', :via => [:get, :post]
  match 'attachments/contacts_thumbnail/:id(/:size)', :controller => 'attachments', :action => 'contacts_thumbnail', :id => /\d+/, :via => :get

app/views/common/_address_form.html.erb
<p class="address">
<label><%= l(:label_crm_address) %></label>
<%= f.text_field :street1, :no_label => true, :placeholder => l(:label_crm_street1), :style => "width:90%;"  -%></p>
<p class="address street2"><%= f.text_field :street2, :no_label => true, :placeholder => l(:label_crm_street2) -%></p>
<p class="address city"><%= f.text_field :city, :no_label => true, :placeholder => l(:label_crm_city) -%> </p>
<p class="address region"><%= f.text_field :region, :no_label => true, :placeholder => l(:label_crm_region) -%></p>
<p class="address postcode"><%= f.text_field :postcode, :no_label => true, :placeholder => l(:label_crm_postcode), :size => 12 -%></p>
<p class="address country"><%= f.select :country_code, countries_options_for_select(f.object.country_code),  :no_label => true, :placeholder => l(:label_crm_country), :include_blank => true  -%></p>

app/views/common/_contact_data.html.erb
<% actions ||= "" %>
<table class="note_data" id="contact_data_<%= contact_data.id %>">
	<tr>
		<td class="avatar"><%= link_to avatar_to(contact_data, :size => "32"),  note_source_url(contact_data), :id => "avatar" %></td>
		<td class="name">
			<h4 class="contacts_header">
				<%= link_to contact_data.name, note_source_url(contact_data) %>
			</h4>
			<%= contact_data.info %>
		</td>
		<% if !actions.blank? %>
		<td>
		   <%= actions %>
		</td>
		<% end %>
	</tr>
</table>

app/views/common/_contact_tabs.html.erb
<% selected_tab = params[:tab] ? params[:tab].to_s : tabs.first[:name] %>

<div class="tabs">
  <ul>
    <% tabs.each do |tab| -%>
        <li><%= link_to tab[:label], tabs_contact_path(@contact, :tab => tab[:name]),
                        :id => "tab-#{tab[:name]}",
                        :class => (tab[:name] != selected_tab ? 'tab-header' : 'selected tab-header'),
                        :data => { :name => tab[:name], :partial => tab[:partial], :project_id => @project},
                        :onclick => "showContactTab('#{tab[:name]}'); this.blur(); return false;" %></li>
    <% end -%>
  </ul>
  <div class="tabs-buttons" style="display:none;">
    <button class="tab-left" onclick="moveTabLeft(this);"></button>
    <button class="tab-right" onclick="moveTabRight(this);"></button>
  </div>
</div>

<% tabs.each do |tab| %>
    <% selected = tab[:name] == selected_tab %>
    <div class='tab-placeholder tab-content <%= 'active loaded' if selected %>' id='tab-placeholder-<%= tab[:name] %>' style='<%= "display: block" if selected %>'>
      <%= render(:partial => tab[:partial]) if selected %>
    </div>
<% end %>
<script type='text/javascript'>
  $(document).ready(displayTabsButtons);
  $(window).resize(displayTabsButtons);
  $(document).ready(function(){ setupDeferredTabs('<%= load_tab_contact_path(@contact) %>') });
</script>

app/views/common/_contacts_select2_data.html.erb
<script type="text/javascript">
  var field_formats = ['contact', 'company'];
  var contact_filter_urls =  {
    'company': "<%= auto_complete_contacts_path(:project_id => (ContactsSetting.cross_project_contacts? ? nil : @project), :is_company => true) %>",
    'contact': "<%= auto_complete_contacts_path(:project_id => (ContactsSetting.cross_project_contacts? ? nil : @project)) %>",
  }
</script>

app/views/common/_notes_attachments.html.erb
<% if notes_attachments.any? %>
<h3><%= l(:label_attachment_plural) %></h3>
<%= render :partial => 'attachments/links', :locals => {:attachments => notes_attachments, :options  => {}} %>
<% end %>

app/views/common/_recently_viewed.html.erb
<h3><%= l(:label_crm_recently_viewed) %></h3>
<div id="recently_viewed">
	<%= render :partial => 'common/contact_data', :collection => RecentlyViewed.includes(:viewed).last(5).map(&:viewed).select{|v| !v.blank? && v.visible?} %>
</div>

app/views/common/_responsible_user.html.erb
<% 	if responsible_user.assigned_to %>
<h3><%= l(:label_crm_assigned_to) %></h3>
<div id="responsible_user">
	<ul>
		<li>
			<%= (avatar(responsible_user.assigned_to, :size => "16").to_s + link_to_user(responsible_user.assigned_to, :class => 'user').to_s).html_safe  %>
		</li>
	</ul>
</div>
<% end %>

app/views/common/_sidebar.html.erb
<%= call_hook(:view_contacts_sidebar_top) %>

<h3><%= l(:label_crm_module_plural) %></h3>
<% if User.current.allowed_to?(:view_contacts, @project, :global => true) %>
<%= link_to l(:label_contact_plural), { :controller => 'contacts', :action => 'index', :project_id => @project, :set_filter => 1} %>
 |
 <% end %>

<%= link_to l(:label_crm_note_plural), { :controller => 'contacts', :action => 'contacts_notes', :project_id => @project} %>

<%= call_hook(:view_contacts_sidebar_bottom) %>