config/routes.rb
# This file is a part of Redmine CRM (redmine_contacts) plugin,
# customer relationship management plugin for Redmine
#
# Copyright (C) 2010-2017 RedmineUP
# http://www.redmineup.com/
#
# redmine_contacts is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_contacts is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_contacts.  If not, see <http://www.gnu.org/licenses/>.

#custom routes for this plugin
  resources :contacts, :path_names => {:contacts_notes => 'notes'} do
    collection do
      get :bulk_edit, :context_menu, :edit_mails, :contacts_notes
      post :bulk_edit, :bulk_update, :send_mails, :preview_email
      delete :bulk_destroy
    end
    member do
      get 'tabs/:tab' => 'contacts#show', :as => "tabs"
      get 'load_tab' => 'contacts#load_tab', :as => "load_tab"
    end
    resources :contacts_projects, :path => "projects", :only => [:new, :create, :destroy]
  end

  resources :projects do
    resources :contacts, :path_names => {:contacts_notes => 'notes'} do
      collection do
        get :contacts_notes
      end
    end

  end

  resources :projects do
    resources :crm_queries, :only => [:new, :create]
  end

  resources :crm_queries, :except => [:show]

  resources :notes

  match '/contacts_tags', :controller => 'contacts_tags', :action => 'destroy', :via => :delete

  resources :contacts_tags do
    collection do
      post :merge, :context_menucha
      get :context_menu, :merge
    end
  end

  match 'projects/:project_id/contacts/:contact_id/new_task' => 'contacts_issues#new', :via => :post

  match 'contacts/:contact_id/duplicates' => 'contacts_duplicates#index', :via => [:get, :post]

  match 'projects/:project_id/deal_categories/new' => 'deal_categories#new', :via => [:get, :post]


  match 'auto_completes/taggable_tags' => 'auto_completes#taggable_tags', :via => :get, :as => 'auto_complete_taggable_tags'
  match 'auto_completes/contact_tags' => 'auto_completes#contact_tags', :via => :get, :as => 'auto_complete_contact_tags'
  match 'auto_completes/contacts' => 'auto_completes#contacts', :via => :get, :as => 'auto_complete_contacts'
  match 'auto_completes/companies' => 'auto_completes#companies', :via => :get, :as => 'auto_complete_companies'

  match 'users/new_from_contact/:id' => 'users#new_from_contact', :via => :get
  match 'contacts_duplicates/:action' => 'contacts_duplicates', :via => [:get, :post]
  match 'contacts_duplicates/search' => 'contacts_duplicates#search', :via => :get, :as => 'contacts_duplicates_search'
  match 'contacts_issues/:action' => 'contacts_issues', :via => [:get, :post, :delete, :put]
  match 'contacts_vcf/:action' => 'contacts_vcf', :via => [:get, :post]
  match 'deal_contacts/:action' => 'deal_contacts', :via => [:get, :post, :delete]
  match 'deals_tasks/:action' => 'deals_tasks', :via => [:get, :post, :put]
  match 'contacts_settings/:action' => 'contacts_settings', :via => [:get, :post]
  match 'contacts_mailer/:action' => 'contacts_mailer', :via => [:get, :post]
  match 'attachments/contacts_thumbnail/:id(/:size)', :controller => 'attachments', :action => 'contacts_thumbnail', :id => /\d+/, :via => :get

app/controllers/contacts_duplicates_controller.rb
# This file is a part of Redmine CRM (redmine_contacts) plugin,
# customer relationship management plugin for Redmine
#
# Copyright (C) 2010-2017 RedmineUP
# http://www.redmineup.com/
#
# redmine_contacts is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_contacts is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_contacts.  If not, see <http://www.gnu.org/licenses/>.

class ContactsDuplicatesController < ApplicationController
  unloadable
  helper :contacts

  before_filter :find_project_by_project_id, :authorize, :except => :search
  before_filter :find_contact, :except => :duplicates
  before_filter :find_duplicate, :only => :merge

  helper :contacts

  def index
    @contacts = @contact.duplicates
  end

  def duplicates
    search_first_name = params[:contact][:first_name] if params[:contact] && !params[:contact][:first_name].blank?
    search_last_name = params[:contact][:last_name] if params[:contact] && !params[:contact][:last_name].blank?
    search_middle_name = params[:contact][:middle_name] if params[:contact] && !params[:contact][:middle_name].blank?

    @contact = (Contact.find(params[:contact_id]) if !params[:contact_id].blank?) || Contact.new
    @contact.first_name = search_first_name || ""
    @contact.last_name = search_last_name || ""
    @contact.middle_name = search_middle_name || ""
    respond_to do |format|
      format.html {render :partial => "duplicates", :layout => false if request.xhr?}
    end
  end

  def merge
    @duplicate.notes << @contact.notes
    @duplicate.issues << @contact.issues
    @duplicate.projects << @contact.projects
    @duplicate.email = (@duplicate.emails | @contact.emails).join(', ')
    @duplicate.phone = (@duplicate.phones | @contact.phones).join(', ')

    call_hook(:controller_contacts_duplicates_merge, {:params => params, :duplicate => @duplicate, :contact => @contact})
    @duplicate.tag_list = @duplicate.tag_list | @contact.tag_list
    begin
      Contact.transaction do
        @duplicate.save!
        @duplicate.reload
        @contact.reload
        @contact.destroy
        flash[:notice] = l(:notice_successful_merged)
        redirect_to :controller => "contacts", :action => "show", :project_id => @project, :id => @duplicate
      end
    rescue
      redirect_to :action => "duplicates", :contact_id => @contact, :project_id => @project
    end

  end

  def search
    @contacts = []
    q = (params[:q] || params[:term]).to_s.strip
    if q.present?
      scope = Contact.where({})
      scope = scope.limit(params[:limit] || 10)
      scope = scope.companies if params[:is_company]
      scope = scope.where(["#{Contact.table_name}.id <> ?", params[:contact_id].to_i]) if params[:contact_id]
      @contacts = scope.visible.by_project(@project).live_search(q).to_a.sort!{|x, y| x.name <=> y.name }
    else
      @contacts = @contact.duplicates
    end
    render :layout => false, :partial => 'list'
  end

  private

  def find_duplicate
    @duplicate = Contact.find(params[:duplicate_id])
    render_403 unless @duplicate.editable?
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def find_contact
    @contact = Contact.find(params[:contact_id])
  rescue ActiveRecord::RecordNotFound
    render_404 if !request.xhr?
  end
end

app/views/contacts_duplicates/_duplicates.html.erb
<div id="duplicates">
<% if @contact.duplicates.any? %>
	<% if !@contact.new_record? %>
	<div class="contextual">
		<%= link_to_if_authorized l(:label_crm_merge_duplicate_plural), {:controller => 'contacts_duplicates', :action => 'index', :project_id => @project, :contact_id => @contact} %>
	</div>
	<% end %>

	<h3><%= l(:label_crm_duplicate_plural) %></h3>
	<ul class="box">
	    <% @contact.duplicates.each do |contact| %>
		<li>

		<%= avatar_to contact, :size => "16" %>
		<%= link_to_source contact %>
		<%= "(#{contact.job_title}) " unless contact.job_title.blank? %>
      </li>
		<% end %>
	</ul>


<% end %>
</div>

app/views/contacts_duplicates/_list.html.erb
<% @contacts.each do |contact| %>
  <li>
    <%= radio_button_tag "duplicate_id", contact.id %>
    <%= avatar_to contact, :size => "16" %>
    <%= link_to_source contact %>
    <%= "(#{contact.job_title}) " unless contact.job_title.blank? %>
  </li>
<% end %>

app/views/contacts_duplicates/index.html.erb
<%= breadcrumb link_to(@contact.name, note_source_url(@contact)) %>

<div class="contact_data_header">
	<table class="note_data">
	<tr>

		<td class="avatar"><%= link_to avatar_to(@contact, :size => "32"), note_source_url(@contact), :id => "avatar" %> </td>
        <td class="name">
			<h2 class="note_title">
				<%= l(:label_crm_duplicate_for_plural) %>: <%= @contact.name %>
			</h2>
			   	<p>
				<%= h @contact.job_title %>
				<%= " #{l(:label_crm_at_company)} " unless (@contact.job_title.blank? or @contact.company.blank?) %>
				<% if @contact.is_company && @contact.contact_company %>
					<%= link_to @contact.contact_company.name, note_source_url(@contact.contact_company) %>
				<% else %>
					<%= h @contact.company %>
				<% end %>
				</p>

		 </td>
		</tr>
</table>
</div>

<%= form_tag({:controller => 'contacts_duplicates', :action => 'merge', :project_id => @project, :contact_id => @contact}) do %>
	<div class="box" id="duplicates">
	    <%= text_field_tag(:principal_search, params[:topic_search] , :autocomplete => "off", :placeholder => l(:label_crm_contact_search) ) %>
    <%= javascript_tag "observeSearchfield('principal_search', 'contact_duplicates', '#{escape_javascript contacts_duplicates_search_path(:contact_id => @contact, :by_email => true)}')" %>

		<%= content_tag('div', l(:notice_merged_warning), :class => "flash warning") %>

		<ul id="contact_duplicates">
			<%= render :partial => 'list' %>
		</ul>
	</div>
	<%= submit_tag l(:label_crm_merge_duplicate_plural) %>
<% end %>

<% html_title "#{l(:label_crm_duplicate_plural)} #{@contact.name}" %>

<% content_for :sidebar do %>
	<%= render :partial => 'common/sidebar' %>

	<%= render :partial => 'common/recently_viewed' %>
<% end %>


<% content_for :header_tags do %>
	<%= javascript_include_tag :contacts, :plugin => 'redmine_contacts'  %>
	<%= stylesheet_link_tag :contacts, :plugin => 'redmine_contacts' %>
	<%= stylesheet_link_tag :contacts_sidebar, :plugin => 'redmine_contacts' %>
<% end %>